// Generates src/styles/icons.css with only the Phosphor icons used in src/.
// The full Phosphor stylesheets are ~160KB of render-blocking CSS; this keeps
// just the glyphs we reference. Runs automatically before dev/build.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const PKG = path.join(ROOT, 'node_modules/@phosphor-icons/web/src');
const OUT = path.join(ROOT, 'src/styles/icons.css');
const WEIGHTS = { light: 'Light', fill: 'Fill' };

const sources = fs
  .readdirSync(path.join(ROOT, 'src'), { recursive: true })
  .filter((f) => /\.(astro|ts|js|json)$/.test(f))
  .map((f) => fs.readFileSync(path.join(ROOT, 'src', f), 'utf8'))
  .join('\n');

const used = new Set(sources.match(/\bph-[a-z0-9-]+/g) ?? []);

let css = '/* Generated by scripts/build-icons.mjs - do not edit */\n';

for (const [weight, name] of Object.entries(WEIGHTS)) {
  const full = fs.readFileSync(path.join(PKG, weight, 'style.css'), 'utf8');
  const fontUrl = `../../node_modules/@phosphor-icons/web/src/${weight}/Phosphor-${name}.woff2`;

  css += `
@font-face {
  font-family: "Phosphor-${name}";
  src: url("${fontUrl}") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

.ph-${weight} {
  font-family: "Phosphor-${name}" !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  letter-spacing: 0;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;

  const rule = new RegExp(`\\.ph-${weight}\\.(ph-[a-z0-9-]+):before\\s*\\{\\s*content:\\s*"([^"]+)";\\s*\\}`, 'g');
  for (const [, icon, content] of full.matchAll(rule)) {
    if (used.has(icon)) css += `.ph-${weight}.${icon}:before { content: "${content}"; }\n`;
  }
}

fs.writeFileSync(OUT, css);
console.log(`icons.css: ${[...used].length} icon classes referenced`);
